name: Matrix CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ opencl-headers pocl-opencl-icd

    - name: Configure CMake
      run: cmake -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure