name: Matrix CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          ocl-icd-opencl-dev \
          clinfo \              # Для диагностики
          pocl-opencl-icd       # CPU-реализация OpenCL

    - name: Verify OpenCL installation
      run: |
        clinfo | head -20 

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release --parallel $(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --parallel $(nproc)
